flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/blog.png"
name: blog_app
description: A Flutter Blog App with social features using Firebase.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.13.0
  provider: ^6.1.1
  uuid: ^4.0.0
  cached_network_image: ^3.3.1
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/175191701450420a90bcw.png
    - lib/assets/loading.json
